<?php
// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>

<ol class="items">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <input class="filter-item-checkbox" name="<?= $filterItem->getId() ?>" id="<?= $filterItem->getId() ?>" data-href="<?= $block->escapeUrl($filterItem->getUrl()) ?>" type="checkbox"<?php if ($filterItem->getIsActive()): ?> checked="checked"<?php endif; ?>/>
                <label for="<?= $filterItem->getId() ?>">
                    <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount()?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?= /* @escapeNotVerified */ __('item')?><?php else:?> <?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </label>
            <?php else:?>
                <input class="filter-item-checkbox" name="<?= $filterItem->getId() ?>" id="<?= $filterItem->getId() ?>" type="checkbox" disabled="disabled"/>
                <label for="<?= $filterItem->getId() ?>">
                    <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?= /* @escapeNotVerified */ __('item') ?><?php else:?> <?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </label>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
